version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: achat
    ports:
      - 3306:3306
    networks:
     - devops
     
  spring-boot:
    image: kaoutherch/achatapp:2.0
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devops 
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?allowPublicKeyRetrieval=true&useSSL=false
    restart: on-failure 
    
    
  angular:
    image: kaoutherch/front
    container_name: front
    ports: 
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - devops
  
networks:
  devops:
