
version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: zeroxcharisma/achat-1.0-s7
    container_name: spring
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure
networks:
  AppNet:
    driver: bridge
