version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: soulaymendocker123/achat-1.0-sk
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     
  
networks:
  AppNet:
