version: '3'
services:
  database:
    image: mysql
    container_name: mysqlmansouri
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: achat
    ports:
      - 3306:3306
    networks:
     - devops
     
  spring-boot:
    image: imenmansouri/jenkins-pipeline
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devops 
    restart: on-failure     
  
networks:
  devops:
