version: '3'
services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - mynet

  spring-boot:
    image: dqntero/spring
    container_name: back
    environment:
      - spring.datasource.url: jdbc:mysql://mysql:3306/achatdb?useSSL=false
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - mynet
    restart: on-failure
    
volumes:
  data:
  
networks:
  mynet:
    driver: bridge
