version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: achat
    ports:
      - 3306:3306
    networks:
     - devops
     
  spring-boot:
    image: kaoutherch/achatapp
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devops 
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/achatdb?allowPublicKeyRetrieval=true&useSSL=false
    restart: on-failure 
    
    
  
networks:
  devops:
