services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306

  spring:
    image: spring
    container_name: back
    ports:
      - 8089:8089
    depends_on:
      - database
    restart: on-failure
