version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: achat
    ports:
      - 3306:3306
    networks:
     - devops
     
  spring-boot:
    image: kaoutherch/achat:1.0
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devops 
    restart: on-failure     
  angular:
    image: kaoutherch/front
    container_name: front
    ports: 
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - devops
  
networks:
  devops:
